### ISSUE TITLE
Misspell on authentication on master

### ISSUE THREAD

**Issue by drageloth** [dilruacs/media_player.sony#2]
Error 
Failed to call service configurator/configure. cannot import name 'AuthenicationResult' from 'sonyapilib.device' (/config/deps/lib/python3.7/site-packages/sonyapilib/device.py)

when trying to authenticate. If I edit the file media_player and replace Authenication with Authentication it works.

Other than that, I get these error whenever I press a button:
Failed to call service media_player/media_next_track. Failed to read command list from device.
Home Cinema is  BDVE4100. I guess maybe not compatible? 

Sorry about replying in general, but I'm not a dev!

**Comment by dilruacs** [comment]
Hi, thanks for testing!

The spelling error is inherited from the upstream library, where it has been fixed before; causing a mismatch.
As I did not re-authenticate my device since, this code wasn't referenced again in my setup so far.

I fixed it, if you check out the code again, you have the correct spelling.

As far as support for the BDV-E4100 is concerned: it should be supported. The code of the library that is being used by this component has been refactored recently and eliminates a few bugs: I will get around to releasing an updated version of this component when I get back from my holiday in a week.

Could you try to retrieve ```http://10.0.0.42:52323/dmr.xml``` (insert the IP of your device) and post it here?

**Comment by drageloth** [comment]
Of course! There you go: 

 

`<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:pnpx="http://schemas.microsoft.com/windows/2008/09/devicefoundation">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <device>
    <deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
    <friendlyName>BLU-RAY HOME THEATRE SYSTEM</friendlyName>
    <manufacturer>Sony Corporation</manufacturer>
    <manufacturerURL>http://www.sony.net/</manufacturerURL>
    <modelName>BLU-RAY HOME THEATRE SYSTEM</modelName>
    <modelNumber>BDV-2013</modelNumber>
    <UDN>uuid:00000000-0000-1010-8000-fcf1521f11ba</UDN>
    <dlna:X_DLNADOC xmlns:dlna="urn:schemas-dlna-org:device-1-0">DMR-1.50</dlna:X_DLNADOC>
    <dlna:X_DLNACAP xmlns:dlna="urn:schemas-dlna-org:device-1-0">playcontainer-1-0</dlna:X_DLNACAP>
    <iconList>
      <icon>
        <mimetype>image/jpeg</mimetype>
        <width>120</width>
        <height>120</height>
        <depth>24</depth>
        <url>/bdv_ej_device_icon_large.jpg</url>
      </icon>
      <icon>
        <mimetype>image/png</mimetype>
        <width>120</width>
        <height>120</height>
        <depth>24</depth>
        <url>/bdv_ej_device_icon_large.png</url>
      </icon>
      <icon>
        <mimetype>image/jpeg</mimetype>
        <width>48</width>
        <height>48</height>
        <depth>24</depth>
        <url>/bdv_ej_device_icon_small.jpg</url>
      </icon>
      <icon>
        <mimetype>image/png</mimetype>
        <width>48</width>
        <height>48</height>
        <depth>24</depth>
        <url>/bdv_ej_device_icon_small.png</url>
      </icon>
    </iconList>
    <serviceList>
      <service>
	<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId> 
        <SCPDURL>/RenderingControlBdvSCPD.xml</SCPDURL>
        <controlURL>/upnp/control/RenderingControl</controlURL>
        <eventSubURL>/upnp/event/RenderingControl</eventSubURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
        <SCPDURL>/ConnectionManagerSCPD.xml</SCPDURL>
        <controlURL>/upnp/control/ConnectionManager</controlURL>
        <eventSubURL>/upnp/event/ConnectionManager</eventSubURL>
      </service>
      <service>
        <serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
        <SCPDURL>/AVTransportSCPD.xml</SCPDURL>
        <controlURL>/upnp/control/AVTransport</controlURL>
        <eventSubURL>/upnp/event/AVTransport</eventSubURL>
      </service>
      <service>
        <serviceType>urn:schemas-sony-com:service:Party:1</serviceType>
        <serviceId>urn:schemas-sony-com:serviceId:Party</serviceId>
        <SCPDURL>/PartySCPD.xml</SCPDURL>
        <controlURL>/upnp/control/Party</controlURL>
        <eventSubURL>/upnp/event/Party</eventSubURL>
      </service>
    </serviceList>
    <av:X_StandardDMR xmlns:av="urn:schemas-sony-com:av">1.1</av:X_StandardDMR>
    <microsoft:magicPacketWakeSupported xmlns:microsoft="urn:schemas-microsoft-com:WMPNSS-1-0">
        1
    </microsoft:magicPacketWakeSupported>
    <pnpx:X_compatibleId>MS_DigitalMediaDeviceClass_DMR_V001</pnpx:X_compatibleId>
    <pnpx:X_deviceCategory>MediaDevices</pnpx:X_deviceCategory>
    <pnpx:X_hardwareId>VEN_0106&amp;DEV_0400&amp;REV_01</pnpx:X_hardwareId>
    <df:X_deviceCategory>Multimedia.DMR</df:X_deviceCategory>
  </device>
</root>
`
[dmr.txt](https://github.com/dilruacs/media_player.sony/files/3099856/dmr.txt)

**Comment by drageloth** [comment]
Case closed as the other problem does not match the topic
