### ISSUE TITLE
Module is broken after 0.92 update on Hassio

### ISSUE THREAD

**Issue by drageloth** [dilruacs/media_player.sony#3]
After update to 0.92 on hassio it doesn't even complete the config check. Error is:
Configuration invalid
Integration sony not found when trying to verify its media_player platform.

**Comment by dilruacs** [comment]
I am unable to replicate this error at the moment.
Does the custom component still exist in the right directory after the hassio update?

**Comment by drageloth** [comment]
@dilruacs Yes and I've reinstalled it just in case. A custom card on lovelace I created to check updates etc is working properly so custom_updater is loaded and on 5.0.0 version.
Can't figure out why.
I've created a folder called sony on folder custom_components and copy the 2 files. Save and check config, all ok. Restart assistant, all ok. 
Go to configuration.yaml to add the media player
- platform: sony
   host: 192.x.x.x
Check config : Integration sony not found when trying to verify its media_player platform.

**Comment by drageloth** [comment]
Ok so figured it out. For some reason hass thought there were files inside sony folder and probably tried to load them. Force deleted the folder from command line, recreated it and voila! Case closed! When you have the time I'd be grateful to check the other problem I still have with the error "Failed to read command list from device!

**Comment by dilruacs** [comment]
@drageloth Thanks for the update, I was just installing a fresh HassIO to try to replicate your problem.
I will have a look at the other issue later today.
